spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: rent-service
          uri: lb://rent-service
          predicates:
            - Path=/v1/rent/**,/v1/register/**
      discovery:
        locator:
          enabled: true

server:
  port: 8890

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true